### ISSUE TITLE
The `fromInfos` prop in the `meltSpore` API was removed

### ISSUE THREAD

**Issue by ShookLyngs** [sporeprotocol/spore-docs#53]
The current version of the melt-spore recipe has a `fromInfos` prop specified:
https://github.com/sporeprotocol/spore-docs/blob/main/docs/recipes/melt-spore.mdx#L26

See changes made in the spore-sdk here:
https://github.com/sporeprotocol/spore-sdk/pull/42

Update suggestions:
- Remove the `fromInfos` prop from the recipe as it's not needed to build the transaction.
- Change the line to: `changeAddress: CHANGE_ADDRESS` for where the capacity should be returned to.

**Comment by anipenguin** [comment]
in https://github.com/sporeprotocol/spore-sdk/pull/42/commits/7e644294551f78056f2e883c7bf99fcb9777660e#diff-88f7c4ff49dd80a5adae906dc761e08e273ea642e6021639f9f7d2f52eb4f279 you wrote 

> changeAddress: Specifies the change cell's ownership.

can you clarify what you mean by that?

> changeAddress: CHANGE_ADDRESS for where the capacity should be returned to.

to confirm, CHANGE_ADDRESS is the address specified to receive the capacity of the melted spore, can it be any address other than the original owner's address?

**Comment by ShookLyngs** [comment]
> to confirm, CHANGE_ADDRESS is the address specified to receive the capacity of the melted spore, can it be any address other than the original owner's address?

Yes, it can be any address. And the prop is optional, if you leave it empty, the capacity will be returned to the owner of the Spore.

**Comment by anipenguin** [comment]
resolved by 

- https://github.com/sporeprotocol/spore-docs/pull/56
